services:
  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.91.0
    restart: always
    command:
      - --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./collector/otel-collector.yml:/etc/otelcol-cont/otel-collector.yml
    ports:
      - '8889'
      - '4317'
      - '4318'
    networks:
      - tracing_net
    depends_on:
      - tempo
      - loki

  tempo:
    container_name: tempo
    restart: always
    image: grafana/tempo:latest
    command: ['-config.file=/etc/tempo.yml']
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - '4317'
      - '3200'
    networks:
      - tracing_net

  loki:
    image: grafana/loki:latest
    restart: always
    container_name: loki
    ports:
      - '3100'
    # volumes:
    # - ./loki/loki-config.yml:/etc/loki/local-config.yml
    #   - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - tracing_net

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
    ports:
      - '9090:9090'
    depends_on:
      - collector
    networks:
      - tracing_net

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - tracing_net

networks:
  tracing_net:
    external: true

volumes:
  grafana_data:
  loki_data:
  prometheus_data:
