groups:
  - name: InstanceMonitoring
    rules:
      - alert: InstanceDown
        expr: probe_http_status_code{instance='http://web-app:8080', job='blackbox'} == 0 or probe_http_status_code{instance='http://web-app:8080', job='blackbox'} == 500
        for: 10s
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.instance }} (job: {{ $labels.job }}) has been down for more than 10 seconds.'
          summary: 'Instance {{ $labels.instance }} is down'
