global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'web-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web-app:8080']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
